baseurl:
title: Veda Cooperative
author: Veda Cooperative
simple_search: http://google.com/search
description: A way of working together.
name: veda
markdown: kramdown
markdown_ext: "md"
timezone: Europe/Lisbon
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "guide"
      type: "pages"
    values:
      layout: "method-booklet"
